# Generated by Django 5.2.7 on 2025-10-14 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'New Assignment'), ('grade', 'Grade Published'), ('attendance', 'Attendance Marked'), ('fee', 'Fee Payment'), ('announcement', 'Announcement'), ('resource', 'New Resource')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_n_user_id_5c2164_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx'),
        ),
    ]
