# Generated by Django 5.2.7 on 2025-10-03 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_order', models.IntegerField()),
                ('slot_type', models.CharField(choices=[('class', 'Class Period'), ('break', 'Break'), ('lunch', 'Lunch')], default='class', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slot_order'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('baby_sitting', 'Baby Sitting'), ('pre_school', 'Pre-School'), ('primary', 'Primary'), ('jhs', 'Junior High School')], max_length=20)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('exam_location', models.CharField(max_length=200)),
                ('max_students', models.IntegerField(default=50)),
                ('registered_students', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Excellence Academy', max_length=200)),
                ('school_motto', models.CharField(blank=True, max_length=200)),
                ('school_address', models.TextField()),
                ('school_phone', models.CharField(max_length=20)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_website', models.URLField(blank=True)),
                ('current_academic_year', models.CharField(max_length=20)),
                ('academic_year_start', models.DateField()),
                ('academic_year_end', models.DateField()),
                ('current_term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], max_length=20)),
                ('term_start_date', models.DateField()),
                ('term_end_date', models.DateField()),
                ('grading_system', models.CharField(choices=[('percentage', 'Percentage (0-100)'), ('letter', 'Letter Grade (A-F)'), ('gpa', 'GPA (0-4.0)')], default='percentage', max_length=20)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('application_fee', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('entrance_exam_required', models.BooleanField(default=True)),
                ('exam_duration_minutes', models.IntegerField(default=120)),
                ('exam_pass_percentage', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='academics.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academics.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'time_slot__slot_order'],
                'unique_together': {('timetable', 'day_of_week', 'time_slot')},
            },
        ),
    ]
