# Generated by Django 5.2.6 on 2025-11-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_teachingresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingresource',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
