# Generated by Django 5.2.6 on 2025-11-23 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_teachingresource'),
        ('admissions', '0003_alter_studentapplication_options_and_more'),
        ('grades', '0002_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='grade',
            new_name='score',
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned'), ('late', 'Late Submission')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='admissions.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'due_date'], name='grades_assi_status_01df1f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_obj', 'status'], name='grades_assi_class_o_110a46_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='grades_assi_assignm_eec512_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='grades_assi_student_aec541_idx'),
        ),
    ]
