# Generated by Django 5.2.6 on 2025-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_rename_grade_assignmentsubmission_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], default='first', max_length=20),
        ),
    ]
