# Generated by Django 5.2.6 on 2025-12-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], default='first', max_length=20),
        ),
    ]
