# Generated by Django 5.2.6 on 2025-10-02 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('exam_scheduled', 'Exam Scheduled'), ('exam_completed', 'Exam Completed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('department', models.CharField(choices=[('baby_sitting', 'Baby Sitting'), ('pre_school', 'Pre-School'), ('primary', 'Primary'), ('jhs', 'Junior High School')], max_length=20)),
                ('learner_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('applying_for_class', models.CharField(max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('residential_address', models.TextField()),
                ('nationality', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('languages_spoken', models.CharField(max_length=200)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('has_health_challenge', models.BooleanField(default=False)),
                ('health_challenge_details', models.TextField(blank=True)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergies_details', models.TextField(blank=True)),
                ('medication_details', models.TextField(blank=True)),
                ('insurance_company', models.CharField(blank=True, max_length=200)),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('insurance_card', models.FileField(blank=True, null=True, upload_to='applications/insurance/')),
                ('parents_status', models.CharField(blank=True, max_length=100)),
                ('declaration_name', models.CharField(max_length=200)),
                ('signature', models.FileField(blank=True, null=True, upload_to='applications/signatures/')),
                ('declaration_date', models.DateField()),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('academic_year', models.CharField(max_length=20)),
                ('roll_number', models.CharField(blank=True, max_length=10)),
                ('residential_address', models.TextField()),
                ('nationality', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('has_health_challenge', models.BooleanField(default=False)),
                ('health_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('admission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.studentapplication')),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('promotion_type', models.CharField(choices=[('promoted', 'Promoted'), ('repeated', 'Repeated')], max_length=20)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('from_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from', to='academics.class')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='admissions.student')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='academics.class')),
            ],
        ),
    ]
