# Generated by Django 5.2.7 on 2025-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='declaration_date',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='declaration_name',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='signature',
        ),
        migrations.AddField(
            model_name='student',
            name='other_names',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='parent_occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='parent_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=50),
        ),
    ]
