# Generated by Django 5.2.7 on 2025-10-06 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_studentapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentapplication',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='declaration_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='applications/signatures/'),
        ),
    ]
